---
apiVersion: v1
kind: Service
metadata:
  name: benchtool-service
  labels:
    app: benchtool
spec:
  type: ClusterIP
  selector:
    app: benchtool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
