---
apiVersion: v1
kind: ConfigMap
metadata:
  name: benchtool-workflow-1
  labels:
    app: benchtool
data:
  workflow.yaml: |
    queries:
      - expr_template: sum(<<.Name>>{<<.Matchers>>})
        interval: 1m
        num_queries: 3
        series_type: gauge-random
      - expr_template: sum(<<.Name>>{<<.Matchers>>})
        interval: 1m
        num_queries: 5
        series_type: gauge-zero
        time_range: 2h
    replicas: 75
    series:
      - labels:
          - name: label_01
            unique_values: 100
            value_prefix: label_value_01
          - name: label_02
            unique_values: 100
            value_prefix: label_value_02
        name: metric_counter_one_01
        static_labels:
            static: "true"
        type: counter-one
      - labels:
          - name: label_01
            unique_values: 100
            value_prefix: label_value_01
          - name: label_02
            unique_values: 100
            value_prefix: label_value_02
        name: metric_counter_random_01
        static_labels:
            static: "true"
        type: counter-random
      - labels:
          - name: label_01
            unique_values: 100
            value_prefix: label_value_01
          - name: label_02
            unique_values: 100
            value_prefix: label_value_02
        name: metric_gauge_random_01
        static_labels:
            static: "true"
        type: gauge-random
      - labels:
          - name: label_01
            unique_values: 100
            value_prefix: label_value_01
          - name: label_02
            unique_values: 100
            value_prefix: label_value_02
        name: metric_gauge_zero_01
        static_labels:
            static: "true"
        type: gauge-zero
      - labels:
          - name: label_011
            unique_values: 100
            value_prefix: label_value_011
          - name: label_021
            unique_values: 100
            value_prefix: label_value_021
        name: metric_counter_one_011
        static_labels:
            static: "true"
        type: counter-one
      - labels:
          - name: label_011
            unique_values: 100
            value_prefix: label_value_011
          - name: label_021
            unique_values: 100
            value_prefix: label_value_021
        name: metric_counter_random_011
        static_labels:
            static: "true"
        type: counter-random
      - labels:
          - name: label_011
            unique_values: 100
            value_prefix: label_value_011
          - name: label_021
            unique_values: 100
            value_prefix: label_value_021
        name: metric_gauge_random_011
        static_labels:
            static: "true"
        type: gauge-random
      - labels:
          - name: label_011
            unique_values: 100
            value_prefix: label_value_011
          - name: label_021
            unique_values: 100
            value_prefix: label_value_021
        name: metric_gauge_zero_011
        static_labels:
            static: "true"
        type: gauge-zero
    write_options:
        batch_size: 1000
        interval: 15s
        timeout: 100s

